-- 학생회 건의함 DB 설정
-- Supabase 대시보드의 SQL Editor 에 통째로 붙여 실행합니다.
-- 여러 번 실행해도 결과가 같습니다.

begin;


-- 0. 건의사항 표
--    이미 있으면 건드리지 않습니다.

create table if not exists public.suggestions (
    id bigint generated by default as identity primary key,
    name text not null,
    is_anonymous boolean,
    title text,
    content text,
    status text,
    created_at timestamptz default now()
);

alter table public.suggestions enable row level security;


-- 1. 관리자 명단
--    로그인만 하면 누구나 건의를 볼 수 있던 것을
--    이 표에 있는 계정만 볼 수 있게 바꿉니다.

create table if not exists public.admins (
    user_id uuid primary key references auth.users (id) on delete cascade,
    created_at timestamptz not null default now()
);

alter table public.admins enable row level security;

revoke all on public.admins from anon, authenticated;
grant select on public.admins to authenticated;

drop policy if exists "Admins can view own row" on public.admins;

create policy "Admins can view own row"
    on public.admins
    for select
    to authenticated
    using (user_id = (select auth.uid()));


-- 2026-10-05 이전에 대시보드에서 만든 계정을 관리자로 등록

insert into public.admins (user_id)
select id
from auth.users
where created_at < '2026-10-05 00:00+00'
on conflict do nothing;


-- 2. 건의사항 정책

drop policy if exists "Allow admins to view suggestions" on public.suggestions;
drop policy if exists "Allow admins to update suggestions" on public.suggestions;
drop policy if exists "Allow admins to delete suggestions" on public.suggestions;
drop policy if exists "Allow students to submit suggestions" on public.suggestions;

create policy "Allow admins to view suggestions"
    on public.suggestions
    for select
    to authenticated
    using (
        exists (
            select 1
            from public.admins
            where admins.user_id = (select auth.uid())
        )
    );

create policy "Allow admins to update suggestions"
    on public.suggestions
    for update
    to authenticated
    using (
        exists (
            select 1
            from public.admins
            where admins.user_id = (select auth.uid())
        )
    )
    with check (
        exists (
            select 1
            from public.admins
            where admins.user_id = (select auth.uid())
        )
    );

create policy "Allow admins to delete suggestions"
    on public.suggestions
    for delete
    to authenticated
    using (
        exists (
            select 1
            from public.admins
            where admins.user_id = (select auth.uid())
        )
    );

-- 관리자로 로그인한 브라우저에서도 제출할 수 있게 authenticated 를 넣습니다.
-- 처음부터 처리 완료로 넣지 못하게 status 를 확인합니다.

create policy "Allow students to submit suggestions"
    on public.suggestions
    for insert
    to anon, authenticated
    with check (status = 'waiting');


-- 3. 화면에서만 확인하던 조건을 DB 에도 둡니다.

alter table public.suggestions
    alter column title set not null,
    alter column content set not null,
    alter column status set not null,
    alter column status set default 'waiting';

alter table public.suggestions
    drop constraint if exists suggestions_name_check,
    drop constraint if exists suggestions_title_check,
    drop constraint if exists suggestions_content_check,
    drop constraint if exists suggestions_status_check;

alter table public.suggestions
    add constraint suggestions_name_check
        check (btrim(name) <> '' and char_length(name) <= 10),
    add constraint suggestions_title_check
        check (btrim(title) <> '' and char_length(title) <= 25),
    add constraint suggestions_content_check
        check (btrim(content) <> '' and char_length(content) <= 500),
    add constraint suggestions_status_check
        check (status in ('waiting', 'complete'));


-- 4. 욕설 검사
--    script.js 의 검사와 같은 방식입니다. 낱말을 바꾸면 양쪽을 같이 바꿉니다.

create or replace function public.check_suggestion_content()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
    text_to_check text;
    allowed text;
    blocked text;
begin
    -- 기호만 지우고 띄어쓰기는 남깁니다.
    -- 띄어쓰기까지 지우면 "수업 시 발표" 같은 글이 막힙니다.
    text_to_check :=
        regexp_replace(
            lower(
                coalesce(new.name, '') || ' ' ||
                coalesce(new.title, '') || ' ' ||
                coalesce(new.content, '')
            ),
            '[[:punct:]]',
            '',
            'g'
        );

    -- 욕설이 아닌 낱말
    foreach allowed in array array[
        '시발점'
    ]
    loop
        text_to_check := replace(text_to_check, allowed, ' ');
    end loop;

    foreach blocked in array array[
        '씨발',
        '시발',
        '병신',
        '개새끼',
        'ㅅㅂ',
        'ㅄ',
        'fuck',
        'shit'
    ]
    loop
        if strpos(text_to_check, lower(blocked)) > 0 then
            raise exception '부적절한 표현이 포함되어 있습니다.';
        end if;
    end loop;

    return new;
end;
$function$;

drop trigger if exists check_suggestion_content_trigger on public.suggestions;

create trigger check_suggestion_content_trigger
    before insert or update of name, title, content
    on public.suggestions
    for each row
    execute function public.check_suggestion_content();


notify pgrst, 'reload schema';

commit;
